local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

google:
  service: GCS
  project: <%= Rails.application.credentials.dig(:google, :project_id) %>
  credentials: <%= Rails.root.join("config/secrets/gcs.keyfile") %>
  bucket: airapp_storage_bucket