local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

google:
  service: GCS
  project: <%= Rails.application.credentials.dig(:google, :project_id) %>
  credentials: {
    type: "<%= Rails.application.credentials.dig(:google, :type) %>",
    project_id: "<%= Rails.application.credentials.dig(:google, :project_id) %>",
    private_key_id: "<%= Rails.application.credentials.dig(:google, :private_key_id) %>",
    private_key: "<%= Rails.application.credentials.dig(:google, :private_key) %>",
    client_email: "<%= Rails.application.credentials.dig(:google, :client_email) %>",
    client_id: "<%= Rails.application.credentials.dig(:google, :client_id) %>",
    auth_uri: "<%= Rails.application.credentials.dig(:google, :auth_uri) %>",
    token_uri: "<%= Rails.application.credentials.dig(:google, :token_uri) %>",
    auth_provider_x509_cert_url: "<%= Rails.application.credentials.dig(:google, :auth_provider_x509_cert_url) %>",
    client_x509_cert_url: "<%= Rails.application.credentials.dig(:google, :client_x509_cert_url) %>"
  }
  bucket: airapp_storage_bucket